import "~/styles/globals.css";

import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";

import {Inter} from 'next/font/google';
import { Header } from "./_components/header";
import { Discount } from "./_components/Discount";

const inter = Inter({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body className="bg-[#F4F4F4]" suppressHydrationWarning={true}>
        
        <TRPCReactProvider>
          <Header/>
          <Discount/>
          {children}
          </TRPCReactProvider>
      </body>
    </html>
  );
}
